/*
 * generated by Xtext
 */
package io.getgauge.validation

import com.thoughtworks.gauge.eclipse.util.GaugeProjectUtil
import io.getgauge.StepUtil
import io.getgauge.spec.SpecPackage
import io.getgauge.spec.Step
import org.eclipse.xtext.validation.Check

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class SpecValidator extends AbstractSpecValidator {

	public static val STEP_IMPLEMTENTATION_NOT_FOUND = 'Step implementation not found'
	@Check
	def checkStepImplementationExists(Step step) {
		val stepText = StepUtil.getStepText(step);
		for(s : GaugeProjectUtil.getImplementedSteps()){
			if(GaugeProjectUtil.getParsedText(stepText).equals(s)) {
				return;
			}
		}
		warning(STEP_IMPLEMTENTATION_NOT_FOUND, 
				SpecPackage.Literals.STEP__DEFINITION,
				STEP_IMPLEMTENTATION_NOT_FOUND)
	}
	
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
}
