/*
* generated by Xtext
*/
package io.getgauge.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;


@Singleton
public class SpecGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Assignment cDefinitionsAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cDefinitionsAlternatives_0 = (Alternatives)cDefinitionsAssignment.eContents().get(0);
		private final RuleCall cDefinitionsSpecParserRuleCall_0_0 = (RuleCall)cDefinitionsAlternatives_0.eContents().get(0);
		private final RuleCall cDefinitionsScenarioParserRuleCall_0_1 = (RuleCall)cDefinitionsAlternatives_0.eContents().get(1);
		private final RuleCall cDefinitionsStepParserRuleCall_0_2 = (RuleCall)cDefinitionsAlternatives_0.eContents().get(2);
		private final RuleCall cDefinitionsCommentParserRuleCall_0_3 = (RuleCall)cDefinitionsAlternatives_0.eContents().get(3);
		private final RuleCall cDefinitionsTagsParserRuleCall_0_4 = (RuleCall)cDefinitionsAlternatives_0.eContents().get(4);
		
		/// *
		// * TODO
		// * - Newline at beginning of file has an error
		// * - Errors if last line is not a newline
		// * / Model:
		//	definitions+=(Spec | Scenario | Step | Comment | Tags)*;
		public ParserRule getRule() { return rule; }

		//definitions+=(Spec | Scenario | Step | Comment | Tags)*
		public Assignment getDefinitionsAssignment() { return cDefinitionsAssignment; }

		//Spec | Scenario | Step | Comment | Tags
		public Alternatives getDefinitionsAlternatives_0() { return cDefinitionsAlternatives_0; }

		//Spec
		public RuleCall getDefinitionsSpecParserRuleCall_0_0() { return cDefinitionsSpecParserRuleCall_0_0; }

		//Scenario
		public RuleCall getDefinitionsScenarioParserRuleCall_0_1() { return cDefinitionsScenarioParserRuleCall_0_1; }

		//Step
		public RuleCall getDefinitionsStepParserRuleCall_0_2() { return cDefinitionsStepParserRuleCall_0_2; }

		//Comment
		public RuleCall getDefinitionsCommentParserRuleCall_0_3() { return cDefinitionsCommentParserRuleCall_0_3; }

		//Tags
		public RuleCall getDefinitionsTagsParserRuleCall_0_4() { return cDefinitionsTagsParserRuleCall_0_4; }
	}

	public class SpecElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Spec");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cNumberSignSpaceKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNameTextPartParserRuleCall_0_1_0 = (RuleCall)cNameAssignment_0_1.eContents().get(0);
		private final RuleCall cSINGLE_NLTerminalRuleCall_0_2 = (RuleCall)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cNameAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cNameTextPartParserRuleCall_1_0_0 = (RuleCall)cNameAssignment_1_0.eContents().get(0);
		private final RuleCall cSINGLE_NLTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cEqualsSignKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final RuleCall cSINGLE_NLTerminalRuleCall_1_3 = (RuleCall)cGroup_1.eContents().get(3);
		
		//// Two formats of Markdown H1
		//Spec:
		//	"# " name+=TextPart+ SINGLE_NL+ | name+=TextPart+ SINGLE_NL "="+ SINGLE_NL+;
		public ParserRule getRule() { return rule; }

		//"# " name+=TextPart+ SINGLE_NL+ | name+=TextPart+ SINGLE_NL "="+ SINGLE_NL+
		public Alternatives getAlternatives() { return cAlternatives; }

		//"# " name+=TextPart+ SINGLE_NL+
		public Group getGroup_0() { return cGroup_0; }

		//"# "
		public Keyword getNumberSignSpaceKeyword_0_0() { return cNumberSignSpaceKeyword_0_0; }

		//name+=TextPart+
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }

		//TextPart
		public RuleCall getNameTextPartParserRuleCall_0_1_0() { return cNameTextPartParserRuleCall_0_1_0; }

		//SINGLE_NL+
		public RuleCall getSINGLE_NLTerminalRuleCall_0_2() { return cSINGLE_NLTerminalRuleCall_0_2; }

		//name+=TextPart+ SINGLE_NL "="+ SINGLE_NL+
		public Group getGroup_1() { return cGroup_1; }

		//name+=TextPart+
		public Assignment getNameAssignment_1_0() { return cNameAssignment_1_0; }

		//TextPart
		public RuleCall getNameTextPartParserRuleCall_1_0_0() { return cNameTextPartParserRuleCall_1_0_0; }

		//SINGLE_NL
		public RuleCall getSINGLE_NLTerminalRuleCall_1_1() { return cSINGLE_NLTerminalRuleCall_1_1; }

		//"="+
		public Keyword getEqualsSignKeyword_1_2() { return cEqualsSignKeyword_1_2; }

		//SINGLE_NL+
		public RuleCall getSINGLE_NLTerminalRuleCall_1_3() { return cSINGLE_NLTerminalRuleCall_1_3; }
	}

	public class ScenarioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Scenario");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cNumberSignNumberSignSpaceKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNameTextPartParserRuleCall_0_1_0 = (RuleCall)cNameAssignment_0_1.eContents().get(0);
		private final RuleCall cSINGLE_NLTerminalRuleCall_0_2 = (RuleCall)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cNameAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cNameTextPartParserRuleCall_1_0_0 = (RuleCall)cNameAssignment_1_0.eContents().get(0);
		private final RuleCall cSINGLE_NLTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final RuleCall cSINGLE_NLTerminalRuleCall_1_3 = (RuleCall)cGroup_1.eContents().get(3);
		
		//// Two formats of Markdown H2
		//Scenario:
		//	"## " name+=TextPart+ SINGLE_NL+ | name+=TextPart+ SINGLE_NL "-"+ SINGLE_NL+;
		public ParserRule getRule() { return rule; }

		//"## " name+=TextPart+ SINGLE_NL+ | name+=TextPart+ SINGLE_NL "-"+ SINGLE_NL+
		public Alternatives getAlternatives() { return cAlternatives; }

		//"## " name+=TextPart+ SINGLE_NL+
		public Group getGroup_0() { return cGroup_0; }

		//"## "
		public Keyword getNumberSignNumberSignSpaceKeyword_0_0() { return cNumberSignNumberSignSpaceKeyword_0_0; }

		//name+=TextPart+
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }

		//TextPart
		public RuleCall getNameTextPartParserRuleCall_0_1_0() { return cNameTextPartParserRuleCall_0_1_0; }

		//SINGLE_NL+
		public RuleCall getSINGLE_NLTerminalRuleCall_0_2() { return cSINGLE_NLTerminalRuleCall_0_2; }

		//name+=TextPart+ SINGLE_NL "-"+ SINGLE_NL+
		public Group getGroup_1() { return cGroup_1; }

		//name+=TextPart+
		public Assignment getNameAssignment_1_0() { return cNameAssignment_1_0; }

		//TextPart
		public RuleCall getNameTextPartParserRuleCall_1_0_0() { return cNameTextPartParserRuleCall_1_0_0; }

		//SINGLE_NL
		public RuleCall getSINGLE_NLTerminalRuleCall_1_1() { return cSINGLE_NLTerminalRuleCall_1_1; }

		//"-"+
		public Keyword getHyphenMinusKeyword_1_2() { return cHyphenMinusKeyword_1_2; }

		//SINGLE_NL+
		public RuleCall getSINGLE_NLTerminalRuleCall_1_3() { return cSINGLE_NLTerminalRuleCall_1_3; }
	}

	public class StepElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Step");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStepAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAsteriskSpaceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_2_0 = (Alternatives)cGroup_2.eContents().get(0);
		private final Assignment cStaticParamsAssignment_2_0_0 = (Assignment)cAlternatives_2_0.eContents().get(0);
		private final RuleCall cStaticParamsStaticParamParserRuleCall_2_0_0_0 = (RuleCall)cStaticParamsAssignment_2_0_0.eContents().get(0);
		private final Assignment cDynamicParamsAssignment_2_0_1 = (Assignment)cAlternatives_2_0.eContents().get(1);
		private final RuleCall cDynamicParamsDynamicParamParserRuleCall_2_0_1_0 = (RuleCall)cDynamicParamsAssignment_2_0_1.eContents().get(0);
		private final RuleCall cWORDTerminalRuleCall_2_0_2 = (RuleCall)cAlternatives_2_0.eContents().get(2);
		private final Keyword cHyphenMinusKeyword_2_0_3 = (Keyword)cAlternatives_2_0.eContents().get(3);
		private final Keyword cEqualsSignKeyword_2_0_4 = (Keyword)cAlternatives_2_0.eContents().get(4);
		private final RuleCall cWSTerminalRuleCall_2_0_5 = (RuleCall)cAlternatives_2_0.eContents().get(5);
		private final RuleCall cSEPARATORSTerminalRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final RuleCall cSINGLE_NLTerminalRuleCall_3_0 = (RuleCall)cGroup_3.eContents().get(0);
		private final RuleCall cSINGLE_NLTerminalRuleCall_3_1 = (RuleCall)cGroup_3.eContents().get(1);
		private final Assignment cTableAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cTableTableParserRuleCall_3_2_0 = (RuleCall)cTableAssignment_3_2.eContents().get(0);
		private final RuleCall cSINGLE_NLTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//// Markdown Unordered List - can contain parameters, Static (i.e. "foo") or Dynamic (i.e. <bar>)
		//// Can also optionally have a Table associated
		//Step:
		//	{Step} "* " ((staticParams+=StaticParam | dynamicParams+=DynamicParam | WORD | "-" | "=" | WS) SEPARATORS*)+
		//	(SINGLE_NL SINGLE_NL* table=Table)? SINGLE_NL+;
		public ParserRule getRule() { return rule; }

		//{Step} "* " ((staticParams+=StaticParam | dynamicParams+=DynamicParam | WORD | "-" | "=" | WS) SEPARATORS*)+ (SINGLE_NL
		//SINGLE_NL* table=Table)? SINGLE_NL+
		public Group getGroup() { return cGroup; }

		//{Step}
		public Action getStepAction_0() { return cStepAction_0; }

		//"* "
		public Keyword getAsteriskSpaceKeyword_1() { return cAsteriskSpaceKeyword_1; }

		//((staticParams+=StaticParam | dynamicParams+=DynamicParam | WORD | "-" | "=" | WS) SEPARATORS*)+
		public Group getGroup_2() { return cGroup_2; }

		//staticParams+=StaticParam | dynamicParams+=DynamicParam | WORD | "-" | "=" | WS
		public Alternatives getAlternatives_2_0() { return cAlternatives_2_0; }

		//staticParams+=StaticParam
		public Assignment getStaticParamsAssignment_2_0_0() { return cStaticParamsAssignment_2_0_0; }

		//StaticParam
		public RuleCall getStaticParamsStaticParamParserRuleCall_2_0_0_0() { return cStaticParamsStaticParamParserRuleCall_2_0_0_0; }

		//dynamicParams+=DynamicParam
		public Assignment getDynamicParamsAssignment_2_0_1() { return cDynamicParamsAssignment_2_0_1; }

		//DynamicParam
		public RuleCall getDynamicParamsDynamicParamParserRuleCall_2_0_1_0() { return cDynamicParamsDynamicParamParserRuleCall_2_0_1_0; }

		//WORD
		public RuleCall getWORDTerminalRuleCall_2_0_2() { return cWORDTerminalRuleCall_2_0_2; }

		//"-"
		public Keyword getHyphenMinusKeyword_2_0_3() { return cHyphenMinusKeyword_2_0_3; }

		//"="
		public Keyword getEqualsSignKeyword_2_0_4() { return cEqualsSignKeyword_2_0_4; }

		//WS
		public RuleCall getWSTerminalRuleCall_2_0_5() { return cWSTerminalRuleCall_2_0_5; }

		//SEPARATORS*
		public RuleCall getSEPARATORSTerminalRuleCall_2_1() { return cSEPARATORSTerminalRuleCall_2_1; }

		//(SINGLE_NL SINGLE_NL* table=Table)?
		public Group getGroup_3() { return cGroup_3; }

		//SINGLE_NL
		public RuleCall getSINGLE_NLTerminalRuleCall_3_0() { return cSINGLE_NLTerminalRuleCall_3_0; }

		//SINGLE_NL*
		public RuleCall getSINGLE_NLTerminalRuleCall_3_1() { return cSINGLE_NLTerminalRuleCall_3_1; }

		//table=Table
		public Assignment getTableAssignment_3_2() { return cTableAssignment_3_2; }

		//Table
		public RuleCall getTableTableParserRuleCall_3_2_0() { return cTableTableParserRuleCall_3_2_0; }

		//SINGLE_NL+
		public RuleCall getSINGLE_NLTerminalRuleCall_4() { return cSINGLE_NLTerminalRuleCall_4; }
	}

	public class StaticParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StaticParam");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameSTATIC_PARAMTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//StaticParam:
		//	name=STATIC_PARAM;
		public ParserRule getRule() { return rule; }

		//name=STATIC_PARAM
		public Assignment getNameAssignment() { return cNameAssignment; }

		//STATIC_PARAM
		public RuleCall getNameSTATIC_PARAMTerminalRuleCall_0() { return cNameSTATIC_PARAMTerminalRuleCall_0; }
	}

	public class DynamicParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DynamicParam");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameDYNAMIC_PARAMTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//DynamicParam:
		//	name=DYNAMIC_PARAM;
		public ParserRule getRule() { return rule; }

		//name=DYNAMIC_PARAM
		public Assignment getNameAssignment() { return cNameAssignment; }

		//DYNAMIC_PARAM
		public RuleCall getNameDYNAMIC_PARAMTerminalRuleCall_0() { return cNameDYNAMIC_PARAMTerminalRuleCall_0; }
	}

	public class TagsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Tags");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTagsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTagsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cWSTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final RuleCall cWORDTerminalRuleCall_4_0 = (RuleCall)cAlternatives_4.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_4_1 = (RuleCall)cAlternatives_4.eContents().get(1);
		private final Keyword cCommaKeyword_4_2 = (Keyword)cAlternatives_4.eContents().get(2);
		private final RuleCall cSINGLE_NLTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		
		//Tags:
		//	{Tags} "tags" WS* ":" (WORD | WS | ",")+ SINGLE_NL+;
		public ParserRule getRule() { return rule; }

		//{Tags} "tags" WS* ":" (WORD | WS | ",")+ SINGLE_NL+
		public Group getGroup() { return cGroup; }

		//{Tags}
		public Action getTagsAction_0() { return cTagsAction_0; }

		//"tags"
		public Keyword getTagsKeyword_1() { return cTagsKeyword_1; }

		//WS*
		public RuleCall getWSTerminalRuleCall_2() { return cWSTerminalRuleCall_2; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//(WORD | WS | ",")+
		public Alternatives getAlternatives_4() { return cAlternatives_4; }

		//WORD
		public RuleCall getWORDTerminalRuleCall_4_0() { return cWORDTerminalRuleCall_4_0; }

		//WS
		public RuleCall getWSTerminalRuleCall_4_1() { return cWSTerminalRuleCall_4_1; }

		//","
		public Keyword getCommaKeyword_4_2() { return cCommaKeyword_4_2; }

		//SINGLE_NL+
		public RuleCall getSINGLE_NLTerminalRuleCall_5() { return cSINGLE_NLTerminalRuleCall_5; }
	}

	public class CommentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Comment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameTextPartParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cNameAlternatives_1_0 = (Alternatives)cNameAssignment_1.eContents().get(0);
		private final RuleCall cNameTextPartParserRuleCall_1_0_0 = (RuleCall)cNameAlternatives_1_0.eContents().get(0);
		private final Keyword cNameHyphenMinusKeyword_1_0_1 = (Keyword)cNameAlternatives_1_0.eContents().get(1);
		private final Keyword cNameEqualsSignKeyword_1_0_2 = (Keyword)cNameAlternatives_1_0.eContents().get(2);
		private final Keyword cNameVerticalLineKeyword_1_0_3 = (Keyword)cNameAlternatives_1_0.eContents().get(3);
		private final Keyword cNameCommaKeyword_1_0_4 = (Keyword)cNameAlternatives_1_0.eContents().get(4);
		private final Keyword cNameColonKeyword_1_0_5 = (Keyword)cNameAlternatives_1_0.eContents().get(5);
		private final RuleCall cSINGLE_NLTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//// Any text that is not a Spec, Scenario, Step or Tag
		//Comment:
		//	name+=TextPart name+=(TextPart | "-" | "=" | "|" | "," | ":")* SINGLE_NL+;
		public ParserRule getRule() { return rule; }

		//name+=TextPart name+=(TextPart | "-" | "=" | "|" | "," | ":")* SINGLE_NL+
		public Group getGroup() { return cGroup; }

		//name+=TextPart
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//TextPart
		public RuleCall getNameTextPartParserRuleCall_0_0() { return cNameTextPartParserRuleCall_0_0; }

		//name+=(TextPart | "-" | "=" | "|" | "," | ":")*
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//TextPart | "-" | "=" | "|" | "," | ":"
		public Alternatives getNameAlternatives_1_0() { return cNameAlternatives_1_0; }

		//TextPart
		public RuleCall getNameTextPartParserRuleCall_1_0_0() { return cNameTextPartParserRuleCall_1_0_0; }

		//"-"
		public Keyword getNameHyphenMinusKeyword_1_0_1() { return cNameHyphenMinusKeyword_1_0_1; }

		//"="
		public Keyword getNameEqualsSignKeyword_1_0_2() { return cNameEqualsSignKeyword_1_0_2; }

		//"|"
		public Keyword getNameVerticalLineKeyword_1_0_3() { return cNameVerticalLineKeyword_1_0_3; }

		//","
		public Keyword getNameCommaKeyword_1_0_4() { return cNameCommaKeyword_1_0_4; }

		//":"
		public Keyword getNameColonKeyword_1_0_5() { return cNameColonKeyword_1_0_5; }

		//SINGLE_NL+
		public RuleCall getSINGLE_NLTerminalRuleCall_2() { return cSINGLE_NLTerminalRuleCall_2; }
	}

	public class TextPartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TextPart");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cWORDTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSEPARATORSTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSTATIC_PARAMTerminalRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cDYNAMIC_PARAMTerminalRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cWSTerminalRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//TextPart:
		//	WORD | SEPARATORS | STATIC_PARAM | DYNAMIC_PARAM | WS;
		public ParserRule getRule() { return rule; }

		//WORD | SEPARATORS | STATIC_PARAM | DYNAMIC_PARAM | WS
		public Alternatives getAlternatives() { return cAlternatives; }

		//WORD
		public RuleCall getWORDTerminalRuleCall_0() { return cWORDTerminalRuleCall_0; }

		//SEPARATORS
		public RuleCall getSEPARATORSTerminalRuleCall_1() { return cSEPARATORSTerminalRuleCall_1; }

		//STATIC_PARAM
		public RuleCall getSTATIC_PARAMTerminalRuleCall_2() { return cSTATIC_PARAMTerminalRuleCall_2; }

		//DYNAMIC_PARAM
		public RuleCall getDYNAMIC_PARAMTerminalRuleCall_3() { return cDYNAMIC_PARAMTerminalRuleCall_3; }

		//WS
		public RuleCall getWSTerminalRuleCall_4() { return cWSTerminalRuleCall_4; }
	}

	public class TableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Table");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cWSTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cHeadingAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cHeadingTableRowParserRuleCall_1_0 = (RuleCall)cHeadingAssignment_1.eContents().get(0);
		private final RuleCall cWSTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cVerticalLineKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final RuleCall cTABLE_ROW_ENDTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final RuleCall cWSTerminalRuleCall_5_0 = (RuleCall)cGroup_5.eContents().get(0);
		private final Assignment cRowsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cRowsTableRowParserRuleCall_5_1_0 = (RuleCall)cRowsAssignment_5_1.eContents().get(0);
		
		//Table:
		//	WS* heading=TableRow WS* ("|" "-"+)+ TABLE_ROW_END (WS* rows+=TableRow)+;
		public ParserRule getRule() { return rule; }

		//WS* heading=TableRow WS* ("|" "-"+)+ TABLE_ROW_END (WS* rows+=TableRow)+
		public Group getGroup() { return cGroup; }

		//WS*
		public RuleCall getWSTerminalRuleCall_0() { return cWSTerminalRuleCall_0; }

		//heading=TableRow
		public Assignment getHeadingAssignment_1() { return cHeadingAssignment_1; }

		//TableRow
		public RuleCall getHeadingTableRowParserRuleCall_1_0() { return cHeadingTableRowParserRuleCall_1_0; }

		//WS*
		public RuleCall getWSTerminalRuleCall_2() { return cWSTerminalRuleCall_2; }

		//("|" "-"+)+
		public Group getGroup_3() { return cGroup_3; }

		//"|"
		public Keyword getVerticalLineKeyword_3_0() { return cVerticalLineKeyword_3_0; }

		//"-"+
		public Keyword getHyphenMinusKeyword_3_1() { return cHyphenMinusKeyword_3_1; }

		//TABLE_ROW_END
		public RuleCall getTABLE_ROW_ENDTerminalRuleCall_4() { return cTABLE_ROW_ENDTerminalRuleCall_4; }

		//(WS* rows+=TableRow)+
		public Group getGroup_5() { return cGroup_5; }

		//WS*
		public RuleCall getWSTerminalRuleCall_5_0() { return cWSTerminalRuleCall_5_0; }

		//rows+=TableRow
		public Assignment getRowsAssignment_5_1() { return cRowsAssignment_5_1; }

		//TableRow
		public RuleCall getRowsTableRowParserRuleCall_5_1_0() { return cRowsTableRowParserRuleCall_5_1_0; }
	}

	public class TableRowElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TableRow");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCellsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cCellsTableCellParserRuleCall_0_0 = (RuleCall)cCellsAssignment_0.eContents().get(0);
		private final RuleCall cTABLE_ROW_ENDTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//TableRow:
		//	cells+=TableCell+ TABLE_ROW_END;
		public ParserRule getRule() { return rule; }

		//cells+=TableCell+ TABLE_ROW_END
		public Group getGroup() { return cGroup; }

		//cells+=TableCell+
		public Assignment getCellsAssignment_0() { return cCellsAssignment_0; }

		//TableCell
		public RuleCall getCellsTableCellParserRuleCall_0_0() { return cCellsTableCellParserRuleCall_0_0; }

		//TABLE_ROW_END
		public RuleCall getTABLE_ROW_ENDTerminalRuleCall_1() { return cTABLE_ROW_ENDTerminalRuleCall_1; }
	}

	public class TableCellElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TableCell");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVerticalLineKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cNameAlternatives_1_0 = (Alternatives)cNameAssignment_1.eContents().get(0);
		private final RuleCall cNameWORDTerminalRuleCall_1_0_0 = (RuleCall)cNameAlternatives_1_0.eContents().get(0);
		private final RuleCall cNameSEPARATORSTerminalRuleCall_1_0_1 = (RuleCall)cNameAlternatives_1_0.eContents().get(1);
		private final RuleCall cNameWSTerminalRuleCall_1_0_2 = (RuleCall)cNameAlternatives_1_0.eContents().get(2);
		
		//TableCell:
		//	"|" name+=(WORD | SEPARATORS | WS)+;
		public ParserRule getRule() { return rule; }

		//"|" name+=(WORD | SEPARATORS | WS)+
		public Group getGroup() { return cGroup; }

		//"|"
		public Keyword getVerticalLineKeyword_0() { return cVerticalLineKeyword_0; }

		//name+=(WORD | SEPARATORS | WS)+
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//WORD | SEPARATORS | WS
		public Alternatives getNameAlternatives_1_0() { return cNameAlternatives_1_0; }

		//WORD
		public RuleCall getNameWORDTerminalRuleCall_1_0_0() { return cNameWORDTerminalRuleCall_1_0_0; }

		//SEPARATORS
		public RuleCall getNameSEPARATORSTerminalRuleCall_1_0_1() { return cNameSEPARATORSTerminalRuleCall_1_0_1; }

		//WS
		public RuleCall getNameWSTerminalRuleCall_1_0_2() { return cNameWSTerminalRuleCall_1_0_2; }
	}
	
	
	private final ModelElements pModel;
	private final SpecElements pSpec;
	private final ScenarioElements pScenario;
	private final StepElements pStep;
	private final StaticParamElements pStaticParam;
	private final DynamicParamElements pDynamicParam;
	private final TagsElements pTags;
	private final CommentElements pComment;
	private final TextPartElements pTextPart;
	private final TableElements pTable;
	private final TableRowElements pTableRow;
	private final TableCellElements pTableCell;
	private final TerminalRule tSINGLE_NL;
	private final TerminalRule tWORD;
	private final TerminalRule tSTATIC_PARAM;
	private final TerminalRule tDYNAMIC_PARAM;
	private final TerminalRule tTABLE_ROW_END;
	private final TerminalRule tWS;
	private final TerminalRule tSEPARATORS;
	
	private final Grammar grammar;

	@Inject
	public SpecGrammarAccess(GrammarProvider grammarProvider) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.pModel = new ModelElements();
		this.pSpec = new SpecElements();
		this.pScenario = new ScenarioElements();
		this.pStep = new StepElements();
		this.pStaticParam = new StaticParamElements();
		this.pDynamicParam = new DynamicParamElements();
		this.pTags = new TagsElements();
		this.pComment = new CommentElements();
		this.pTextPart = new TextPartElements();
		this.pTable = new TableElements();
		this.pTableRow = new TableRowElements();
		this.pTableCell = new TableCellElements();
		this.tSINGLE_NL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SINGLE_NL");
		this.tWORD = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "WORD");
		this.tSTATIC_PARAM = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "STATIC_PARAM");
		this.tDYNAMIC_PARAM = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "DYNAMIC_PARAM");
		this.tTABLE_ROW_END = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "TABLE_ROW_END");
		this.tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "WS");
		this.tSEPARATORS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SEPARATORS");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("io.getgauge.Spec".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	
	/// *
	// * TODO
	// * - Newline at beginning of file has an error
	// * - Errors if last line is not a newline
	// * / Model:
	//	definitions+=(Spec | Scenario | Step | Comment | Tags)*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//// Two formats of Markdown H1
	//Spec:
	//	"# " name+=TextPart+ SINGLE_NL+ | name+=TextPart+ SINGLE_NL "="+ SINGLE_NL+;
	public SpecElements getSpecAccess() {
		return pSpec;
	}
	
	public ParserRule getSpecRule() {
		return getSpecAccess().getRule();
	}

	//// Two formats of Markdown H2
	//Scenario:
	//	"## " name+=TextPart+ SINGLE_NL+ | name+=TextPart+ SINGLE_NL "-"+ SINGLE_NL+;
	public ScenarioElements getScenarioAccess() {
		return pScenario;
	}
	
	public ParserRule getScenarioRule() {
		return getScenarioAccess().getRule();
	}

	//// Markdown Unordered List - can contain parameters, Static (i.e. "foo") or Dynamic (i.e. <bar>)
	//// Can also optionally have a Table associated
	//Step:
	//	{Step} "* " ((staticParams+=StaticParam | dynamicParams+=DynamicParam | WORD | "-" | "=" | WS) SEPARATORS*)+
	//	(SINGLE_NL SINGLE_NL* table=Table)? SINGLE_NL+;
	public StepElements getStepAccess() {
		return pStep;
	}
	
	public ParserRule getStepRule() {
		return getStepAccess().getRule();
	}

	//StaticParam:
	//	name=STATIC_PARAM;
	public StaticParamElements getStaticParamAccess() {
		return pStaticParam;
	}
	
	public ParserRule getStaticParamRule() {
		return getStaticParamAccess().getRule();
	}

	//DynamicParam:
	//	name=DYNAMIC_PARAM;
	public DynamicParamElements getDynamicParamAccess() {
		return pDynamicParam;
	}
	
	public ParserRule getDynamicParamRule() {
		return getDynamicParamAccess().getRule();
	}

	//Tags:
	//	{Tags} "tags" WS* ":" (WORD | WS | ",")+ SINGLE_NL+;
	public TagsElements getTagsAccess() {
		return pTags;
	}
	
	public ParserRule getTagsRule() {
		return getTagsAccess().getRule();
	}

	//// Any text that is not a Spec, Scenario, Step or Tag
	//Comment:
	//	name+=TextPart name+=(TextPart | "-" | "=" | "|" | "," | ":")* SINGLE_NL+;
	public CommentElements getCommentAccess() {
		return pComment;
	}
	
	public ParserRule getCommentRule() {
		return getCommentAccess().getRule();
	}

	//TextPart:
	//	WORD | SEPARATORS | STATIC_PARAM | DYNAMIC_PARAM | WS;
	public TextPartElements getTextPartAccess() {
		return pTextPart;
	}
	
	public ParserRule getTextPartRule() {
		return getTextPartAccess().getRule();
	}

	//Table:
	//	WS* heading=TableRow WS* ("|" "-"+)+ TABLE_ROW_END (WS* rows+=TableRow)+;
	public TableElements getTableAccess() {
		return pTable;
	}
	
	public ParserRule getTableRule() {
		return getTableAccess().getRule();
	}

	//TableRow:
	//	cells+=TableCell+ TABLE_ROW_END;
	public TableRowElements getTableRowAccess() {
		return pTableRow;
	}
	
	public ParserRule getTableRowRule() {
		return getTableRowAccess().getRule();
	}

	//TableCell:
	//	"|" name+=(WORD | SEPARATORS | WS)+;
	public TableCellElements getTableCellAccess() {
		return pTableCell;
	}
	
	public ParserRule getTableCellRule() {
		return getTableCellAccess().getRule();
	}

	//terminal SINGLE_NL:
	//	"\r"? "\n" | EOF;
	public TerminalRule getSINGLE_NLRule() {
		return tSINGLE_NL;
	} 

	//terminal WORD:
	//	("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getWORDRule() {
		return tWORD;
	} 

	//terminal STATIC_PARAM:
	//	"\""->"\"";
	public TerminalRule getSTATIC_PARAMRule() {
		return tSTATIC_PARAM;
	} 

	//terminal DYNAMIC_PARAM:
	//	"<"->">";
	public TerminalRule getDYNAMIC_PARAMRule() {
		return tDYNAMIC_PARAM;
	} 

	//terminal TABLE_ROW_END:
	//	"|" SINGLE_NL;
	public TerminalRule getTABLE_ROW_ENDRule() {
		return tTABLE_ROW_END;
	} 

	//terminal WS:
	//	" " | "\t";
	public TerminalRule getWSRule() {
		return tWS;
	} 

	//terminal SEPARATORS:
	//	!("\r" | "\n" | "a".."z" | "A".."Z" | "0".."9" | "_" | " " | "\t");
	public TerminalRule getSEPARATORSRule() {
		return tSEPARATORS;
	} 
}
