/*
* generated by Xtext
*/
package io.getgauge;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SpecUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return io.getgauge.ui.internal.SpecActivator.getInstance().getInjector("io.getgauge.Spec");
	}
	
}
