/**
 * generated by Xtext
 */
package io.getgauge.ui.contentassist;

import io.getgauge.ui.contentassist.AbstractSpecProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SpecProposalProvider extends AbstractSpecProposalProvider {
}
