/**
 * generated by Xtext
 */
package io.getgauge.validation;

import io.getgauge.validation.AbstractSpecValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SpecValidator extends AbstractSpecValidator {
}
