/*
* generated by Xtext
*/
package io.getgauge;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SpecStandaloneSetup extends SpecStandaloneSetupGenerated{

	public static void doSetup() {
		new SpecStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

