/*
 * generated by Xtext
 */
package io.getgauge;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SpecRuntimeModule extends io.getgauge.AbstractSpecRuntimeModule {

}
