/*
 * generated by Xtext
 */
package io.getgauge.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SpecUiModule extends io.getgauge.ui.AbstractSpecUiModule {
	public SpecUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	 public Class <?extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
	 return SpecHighlightingConfiguration.class;
	 }
	 public Class <?extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator(){
	 return SpecHighlightingCalculator.class;
	 }
}