/*
 * generated by Xtext
 */
package io.getgauge.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSpecValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(io.getgauge.spec.SpecPackage.eINSTANCE);
		return result;
	}
}
